UBUNTU: Start new release
Ignore: yes

Signed-off-by: Tim Gardner <tim.gardner@canonical.com>

diff --git a/debian.master/scripts/sub-flavour b/debian.master/scripts/sub-flavour
--- a/debian.master/scripts/sub-flavour
+++ b/debian.master/scripts/sub-flavour
@@ -14,44 +14,24 @@ install -d "debian/$to_pkg/boot"
 install -m644 debian/$from_pkg/boot/{vmlinuz,System.map,config}-$ABI_RELEASE-$FROM \
 	debian/$to_pkg/boot/
 
-#
-# Print some warnings if there are files in the sub-flavours list
-# that do not actually exist.
-#
 cat ${DEBIAN}/sub-flavours/$TO.list | while read line
 do
 (
 	cd debian/$from_pkg/lib/modules/$ABI_RELEASE-$FROM/kernel;
-	#
-	# If its a wildcard, then check that there are files that match.
-	#
-	if echo "$line" | grep '\*' > /dev/null
+	if ! find $line -name '*.ko' > /dev/null 2>&1
 	then
-		if [ `eval find "$line" -name '*.ko'|wc -l` -lt 1 ]
-		then
-			echo SUB_INST Warning - No files in $line
-		fi
-	#
-	# Else it should be a single file reference.
-	#
-	elif [ ! -f "$line" ]
-	then
-		echo SUB_INST Warning - could not find "$line"
+		#
+		# Not being able to find $line may cause
+		# the next loop (below) to fail.
+		#
+		echo SUB_INST Warning - could not find $line
 	fi
 )
 done
 
 cat ${DEBIAN}/sub-flavours/$TO.list | while read line; do
-	(
-	cd debian/$from_pkg/lib/modules/$ABI_RELEASE-$FROM/kernel;
-	if echo "$line" | grep '\*' > /dev/null
-	then
-		eval find "$line" -name '*.ko'
-	elif [ -f "$line" ]
-	then
-		echo "$line"
-	fi
-	);
+	(cd debian/$from_pkg/lib/modules/$ABI_RELEASE-$FROM/kernel;
+	eval find $line -name '*.ko');
 done | while read mod; do
 	echo "SUB_INST checking: $mod"
 	fromdir="/lib/modules/$ABI_RELEASE-$FROM/"
